using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Authorization;
using Counter.Services;
using Counter.Models;
using System.Threading.Tasks;

namespace FirebaseAuthBE.Controllers
{
    [ApiController]
    [Route("[controller]")]
    public class TestService : ControllerBase
    {
        private static readonly string[] Summaries = new[]
        {
            "Freezing", "Bracing", "Chilly", "Cool", "Mild", "Warm", "Balmy", "Hot", "Sweltering", "Scorching"
        };

        private readonly ILogger<TestService> _logger;
        private readonly ICounterService _counterService;

        public TestService(ILogger<TestService> logger, ICounterService counterService)
        {
            _logger = logger;
            _counterService = counterService;
        }

        [Route("/Weather")]
        [HttpGet]
        public WeatherForecast Get()
        {
            return new WeatherForecast
            {
                Date = DateTime.Now.AddDays(1),
                TemperatureC = 23,
                Summary = Summaries[1]
            };
        }

        [Route("/Count")]
        [HttpGet]
        public Count CurrentCount()
        {
            return new Count
            {
               currentCount = 0,
               userName = "Anonymous"
            };
        }

        [Route("/SecureCount")]
        [HttpGet, Authorize]
        public Count SecureCurrentCount()
        {
            var currentUser = HttpContext.User;
            var userName = currentUser.Claims.ToList().Where(a => a.Type == "name").FirstOrDefault().ToString();

            return new Count
            {
                currentCount = 1,
                userName = userName
            };

            // if not logged in, then redirect...
        }

        // How do we get those mongo ids autogenerated???


        [Route("/CreateCounter")]
        [HttpGet, Authorize]
        public string CreateCounter()
        {
            var currentUser = HttpContext.User;
            var userName = currentUser.Claims.ToList().Where(a => a.Type == "name").FirstOrDefault().ToString();

            _counterService.AddCounter(userName);

            return "Counter added.";
        }

        [Route("/IncrementCounter")]
        [HttpGet, Authorize]
        public async Task<CounterInfo> IncrementCounter()
        {
            var currentUser = HttpContext.User;
            var userName = currentUser.Claims.ToList().Where(a => a.Type == "name").FirstOrDefault().ToString();

            await _counterService.IncrementCounter(userName);

            var updatedCounter = await _counterService.GetCounter(userName);

            return updatedCounter;
        }
    }
}
